name: Yeah Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        version: 7
        run_install: false
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=${pnpm store path}" >> $GITHUB_OUTPUT
    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.VM_PRIVATE_KEY }}
        port: 22
        script: |
          eval "$(ssh-agent -s)"
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd ~/projects/yeah
          pnpm install
          pnpm rollback
          git pull origin master -v
          git status
          pnpm migrate
          pnpm seed
          pnpm setup-es
          pm2 reload ecosystem.config.cjs
