name: Yeah Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.VM_PRIVATE_KEY }}
        port: 22
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd ~/projects/yeah
          pnpm install
          pnpm rollback
          git pull origin master
          git status
          pnpm migrate
          pnpm seed
          pnpm setup-es
          pm2 reload ecosystem.config.cjs
